defaults:
  -
    scope:
      path: "" # tutti i file nel progetto
    values:
      layout: "default"
      
include: [".htaccess"]

# Assicurati che i file HTML vengano serviti correttamente
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
